# Generated by gallery/generate.py; do not edit.
function tempad_gallery:clear
# timedoor-default-up: default orange timedoor marker, up
setblock 172 100 172 tempad:timedoor_marker[up=true]
# timedoor-red-down: red timedoor marker, down
setblock 176 100 172 tempad:timedoor_marker[up=false]{"neoforge:attachments":{"tempad:color":"red"}}
# chronomark-default-down: default orange chronomark, down
setblock 180 100 172 tempad:chronomark[up=false]
# chronomark-cyan-up: cyan chronomark, up
setblock 184 100 172 tempad:chronomark[up=true]{"neoforge:attachments":{"tempad:color":"cyan"}}
# workstation-base-0: north base Tempad, empty
setblock 172 100 176 tempad:workstation[facing=north,has_tape=false]{Inventory:{Size:1,Items:[{Slot:0,id:"tempad:tempad",count:1,components:{"tempad:twister_equipped":0b,"tempad:chronon_content_tempad":0,"tempad:chronon_content_time_twister":0}}]}}
# workstation-base-0: north base Tempad, empty terminal
setblock 171 100 176 tempad:workstation_child[facing=north]
# workstation-base-50: east base Tempad, half charge
setblock 176 100 176 tempad:workstation[facing=east,has_tape=false]{Inventory:{Size:1,Items:[{Slot:0,id:"tempad:tempad",count:1,components:{"tempad:twister_equipped":0b,"tempad:chronon_content_tempad":3000,"tempad:chronon_content_time_twister":0}}]}}
# workstation-base-50: east base Tempad, half charge terminal
setblock 176 100 175 tempad:workstation_child[facing=east]
# workstation-attached-0: south attached Tempad, empty
setblock 180 100 176 tempad:workstation[facing=south,has_tape=true]{Inventory:{Size:1,Items:[{Slot:0,id:"tempad:tempad",count:1,components:{"tempad:twister_equipped":1b,"tempad:chronon_content_tempad":0,"tempad:chronon_content_time_twister":0}}]}}
# workstation-attached-0: south attached Tempad, empty terminal
setblock 181 100 176 tempad:workstation_child[facing=south]
# workstation-attached-100: west attached Tempad, full charge
setblock 184 100 176 tempad:workstation[facing=west,has_tape=false]{Inventory:{Size:1,Items:[{Slot:0,id:"tempad:tempad",count:1,components:{"tempad:twister_equipped":1b,"tempad:chronon_content_tempad":6000,"tempad:chronon_content_time_twister":3000}}]}}
# workstation-attached-100: west attached Tempad, full charge terminal
setblock 184 100 177 tempad:workstation_child[facing=west]
# workstation-empty: empty workstation
setblock 172 100 180 tempad:workstation[facing=south,has_tape=false]
# workstation-empty: empty workstation terminal
setblock 173 100 180 tempad:workstation_child[facing=south]
# projector-off: projector off without card
setblock 176 100 180 tempad:timedoor_projector[facing=south,has_card=false,triggered=false]
# projector-on: projector on with card
setblock 180 100 180 tempad:timedoor_projector[facing=south,has_card=true,triggered=true]
# metronome: metronome stock model
setblock 184 100 180 tempad:metronome
function tempad_gallery:verify
