# Generated by gallery/generate.py; do not edit.
execute unless block 172 100 172 tempad:timedoor_marker[up=true] run tellraw @a {"text":"gallery mismatch: timedoor-default-up","color":"red"}
execute unless block 176 100 172 tempad:timedoor_marker[up=false] run tellraw @a {"text":"gallery mismatch: timedoor-red-down","color":"red"}
execute unless block 180 100 172 tempad:chronomark[up=false] run tellraw @a {"text":"gallery mismatch: chronomark-default-down","color":"red"}
execute unless block 184 100 172 tempad:chronomark[up=true] run tellraw @a {"text":"gallery mismatch: chronomark-cyan-up","color":"red"}
execute unless block 172 100 176 tempad:workstation[facing=north,has_tape=false] run tellraw @a {"text":"gallery mismatch: workstation-base-0","color":"red"}
execute unless block 171 100 176 tempad:workstation_child[facing=north] run tellraw @a {"text":"gallery mismatch: workstation-base-0","color":"red"}
execute unless block 176 100 176 tempad:workstation[facing=east,has_tape=false] run tellraw @a {"text":"gallery mismatch: workstation-base-50","color":"red"}
execute unless block 176 100 175 tempad:workstation_child[facing=east] run tellraw @a {"text":"gallery mismatch: workstation-base-50","color":"red"}
execute unless block 180 100 176 tempad:workstation[facing=south,has_tape=true] run tellraw @a {"text":"gallery mismatch: workstation-attached-0","color":"red"}
execute unless block 181 100 176 tempad:workstation_child[facing=south] run tellraw @a {"text":"gallery mismatch: workstation-attached-0","color":"red"}
execute unless block 184 100 176 tempad:workstation[facing=west,has_tape=false] run tellraw @a {"text":"gallery mismatch: workstation-attached-100","color":"red"}
execute unless block 184 100 177 tempad:workstation_child[facing=west] run tellraw @a {"text":"gallery mismatch: workstation-attached-100","color":"red"}
execute unless block 172 100 180 tempad:workstation[facing=south,has_tape=false] run tellraw @a {"text":"gallery mismatch: workstation-empty","color":"red"}
execute unless block 173 100 180 tempad:workstation_child[facing=south] run tellraw @a {"text":"gallery mismatch: workstation-empty","color":"red"}
execute unless block 176 100 180 tempad:timedoor_projector[facing=south,has_card=false,triggered=false] run tellraw @a {"text":"gallery mismatch: projector-off","color":"red"}
execute unless block 180 100 180 tempad:timedoor_projector[facing=south,has_card=true,triggered=true] run tellraw @a {"text":"gallery mismatch: projector-on","color":"red"}
execute unless block 184 100 180 tempad:metronome run tellraw @a {"text":"gallery mismatch: metronome","color":"red"}
tellraw @a {"text":"Tempad renderer gallery checked","color":"green"}
